<%@ page language="java" contentType="text/html; charset=EUC-KR"
    pageEncoding="EUC-KR"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="EUC-KR">
<title>Insert title here</title>
</head>
<body>

<b>1.Page directives</b><br>
* import: import classes or interfaces
<%@ page import="java.util.Date" %>  
Today is: <%= new Date() %>  

<br><hr>

contentType: defines the MIME type of the HTTP response

<br><hr>

buffer: sets the buffer size in kb to handle output generated by the JSP page.
<%@ page buffer="16kb" %>  
Today is: <%= new java.util.Date() %>  
  
<br><hr>

info: set the info of the JSP page that retrieved later by getServletINfo() method.

<br><hr>
isElgnored: Ignoring the Expression Language or not.
<%@ page isELIgnored="true" %>//Now EL will be ignored  

<br><hr>
errorPage: define the error page

<br><hr>

isErrorPage: declaring the current page as an error page.

<br><hr>

<b>2. Include Directives</b><br>
file(include): inclues the contests of jsp, html or text file.
<%@ include file = "file.html" %>
Today is: <%= java.util.Calendar.getInstance().getTime() %>

<br><hr>

<b>3. Taglib Directives</b><br>
taglib: define a tag library with many tags. By using TLD(Tag Library Descriptor) file, we can define the customized tag.
  
</body>
</html>